branches:
  except:
    - debian

image: Visual Studio 2017

environment:
  matrix:
    - COMPILER: msvc
      COMPILER_VERSION: "15.0" # Visual Studio 2017
      TARGET: x86
      GENERATOR: "NMake Makefiles"

matrix:
  fast_finish: false

configuration: Debug

build:
  parallel: true

before_build:
  - git submodule update --init --recursive

build_script:
  - cmd: cmake --version
  - cmd: mkdir build
  - cmd: cd build
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat"
  - cmd: cmake -DUSE_WERROR=1 -DBE_VERBOSE=1 -DUSE_PRECOMPILED_HEADER=0 -G "NMake Makefiles" -DBUILD_GAME_NACL=0 -DCMAKE_BUILD_TYPE=Debug ..
  - cmd: cmake --build .
