pool:
  vmImage: 'macOS-10.15'

steps:
- script: |
    set -e
    git submodule update --init --recursive
    cmake -Wdev -Wdeprecated -DUSE_PRECOMPILED_HEADER=0 -DUSE_WERROR=1 -DBE_VERBOSE=1 -DUSE_DEBUG_OPTIMIZE=0 -DCMAKE_BUILD_TYPE=Debug -H. -Bbuild
    cmake --build build -- -j`sysctl -n hw.logicalcpu`
  displayName: 'Build'
